#------------------------------------------------------------------------------
# General
#------------------------------------------------------------------------------
name: "Léonard Roussel"
description: "meow description."
language: "en"

url: http://localhost:4000
baseurl: ''

#------------------------------------------------------------------------------
# Markdown processor and code highlighting
#------------------------------------------------------------------------------
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

#------------------------------------------------------------------------------
# Pagination and friendly URLs
#------------------------------------------------------------------------------
paginate: 2
paginate_path: /page-:num
permalink: /:title

#------------------------------------------------------------------------------
# Social sharing, comments and RSS.
#------------------------------------------------------------------------------
disqus-id: yourusername

enable-share: true
instagram: leo.nerd
github: leo-nerd
soundcloud: leo_nerd
mixcloud: leo_nerd

rss-feed-limit: 10
rss-show-full: false

#------------------------------------------------------------------------------
# Configuration, plugins, gems, etc..
#------------------------------------------------------------------------------
source: .
destination: ./_site
plugins: ['jekyll-paginate']

sass:
    style: :compressed
    sass_dir: assets/css/