#------------------------------------------------------------------------------
# General
#------------------------------------------------------------------------------
title: "Léonard Roussel"
description: "Engineer + Designer <br> Audio + Visual <br> Physical + Digital"
language: "en"

url: https://leonardroussel.com
baseurl: 
permalink: /:slug

#------------------------------------------------------------------------------
# Markdown processor and code highlighting
#------------------------------------------------------------------------------
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

#------------------------------------------------------------------------------
# Pagination and friendly URLs
#------------------------------------------------------------------------------
# paginate: 6
# paginate_path: /page-:num
# permalink: /:title

#------------------------------------------------------------------------------
# Social
#------------------------------------------------------------------------------

enable-share: false
instagram: leo.nerd
github: leo-nerd
soundcloud: leo_nerd
mixcloud: leo_nerd

#------------------------------------------------------------------------------
# Configuration, plugins, gems, etc..
#------------------------------------------------------------------------------
source: .
destination: ./_site
plugins: ['jekyll-paginate']

sass:
    style: :compressed
    sass_dir: assets/css/